--- !ditz.rubyforge.org,2008-03-06/project 
name: tkt
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: tkt
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2009-07-14 04:15:16.536228 Z
  log_events: 
  - - 2009-07-10 02:32:26.369472 Z
    - Travis Parker <travis.parker@gmail.com>
    - created
    - ""
  - - 2009-07-14 04:15:16.536281 Z
    - Travis Parker <travis.parker@gmail.com>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-07-11 08:13:17.671465 Z
    - Travis Parker <travis.parker@gmail.com>
    - created
    - ""
labels: []

